on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akscheckcontainerregistry.azurecr.io
        username: ${{ secrets.acr_akscheckcontainerregistry_username }}
        password: ${{ secrets.acr_akscheckcontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/code/azure-vote" -f  "code/azure-vote/Dockerfile" -t akscheckcontainerregistry.azurecr.io/akscluster:${{ github.sha }} --label dockerfile-path=code/azure-vote/Dockerfile
        docker push akscheckcontainerregistry.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksclusternamespace01 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksclusternamespace01`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksclusternamespace01
        container-registry-url: akscheckcontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_akscheckcontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_akscheckcontainerregistry_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksclusternamespace01
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          akscheckcontainerregistry.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth
